version: '3.1'
services:
  stats-server:
    build: ./stats_server
    container_name: stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stat_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: ./main_server
    container_name: main_server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - STAT_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:14-alpine
    container_name: main-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main_server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
